### ISSUE TITLE
Tweak tweet language

### ISSUE THREAD

**Issue by grigs** [cloudfour/pwastats#100]
When the first automated tweet went out, I realized that the tweet didn't contain any of the interesting bits.
https://twitter.com/PWAStats/status/856582720574640128

I'd like to see the tweets contain some of the data from the actual content.

I'm going to experiment with changing IFTT's template, but before I do so, I wanted to record the current template:

```
New PWA Stats resource! This one focuses on {{EntryTitle}}. {{EntryUrl}}
```

**Comment by grigs** [comment]
I changed the template to:

```
{{EntryContent}} {{EntryUrl}} 
```

I'm not sure what will happen if the content is longer than 140 chars.

**Comment by gerardo-rodriguez** [comment]
I guess this happens. 😉 

https://mobile.twitter.com/PWAStats/status/860528866590371840

<img width="623" alt="screen shot 2017-05-05 at 10 21 46 am" src="https://cloud.githubusercontent.com/assets/459757/25756731/aec36514-317c-11e7-9521-c4cb08c80def.png">

**Comment by grigs** [comment]
I saw that. I think it works pretty well. Happy it automatically truncates.
