### ISSUE TITLE
Submission: New Story - Settled

### ISSUE THREAD

**Issue by deanhume** [cloudfour/pwastats#109]
### Summary

[Settled](https://www.settled.co.uk) Reduces Mobile Page Load Times by Nearly 3X and Improves Mobile Experience Through a Progressive Web App

### Source

https://www.thinkwithgoogle.com/intl/en-gb/case-studies/settled-improves-mobile-experience-through-progressive-web-apps.html

### Tags

- Progressive Web App
- Proptech
- Offline
- Service Worker
- Startup

**Comment by grigs** [comment]
YAY DEAN!

Thank you so much for submitting this. I'm working on building the PWA Stats update which means I typically pull the icon from the site's manifest file. Is the site https://www.settled.co.uk? I don't see a manifest for it. Am I looking at the right thing?

**Comment by deanhume** [comment]
Hi Jason 😄 

We have only updated part of our site to a PWA (the user dashboard that signed up users see) - which is why you won't see it on the main site.

Here is a link to the manifest file:

https://hub.settled.co.uk/manifest.json

Hope that helps! Please let me know if you have any questions - and thanks for creating this awesome resource. Very cool stuff!

**Comment by grigs** [comment]
Gerardo pulled this over the finish line when my machine stopped behaving.
https://github.com/cloudfour/pwastats/pull/110
