### ISSUE TITLE
Beezer PWA Builder 

### ISSUE THREAD

**Issue by tartanarmy** [cloudfour/pwastats#122]
### Summary

Beezer.com are democratising the building of PWA apps.  There are over 1.2 billion websites in the world and only around 6 million apps. 

### Source

https://hostingfacts.com/internet-facts-stats-2016/
https://www.statista.com/statistics/276623/number-of-apps-available-in-leading-app-stores/

### Tags

- PWA
- MobileApps

_List all that apply from the [tags directory](../_tags/)._

**Comment by grigs** [comment]
@tartanarmy Thanks for the suggestion. I don't see any data in those links about performance or revenue improvements due to PWAs. We're focused on sharing statistics that show the impact of PWAs. 

If you have something like that share, please feel free to reopen this issue with new citations.
