### ISSUE TITLE
Debenhams

### ISSUE THREAD

**Issue by grigs** [cloudfour/pwastats#124]
> **Note:** This template is for new case study content submissions only. 
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

Debenhams found shopper visits take half the time than they did on the pre-PWA mobile website.

### Source

https://www.mobilemarketer.com/news/debenhams-doubles-speed-of-mobile-site-with-progressive-web-app/509870/

### Tags

- ecommerce

probably others. just trying to document these right now to pick up later.

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by grigs** [comment]
Additional details:
https://www.mobify.com/insights/debenhams-doubled-mobile-site-speed-mobify-pwa/

**Comment by grigs** [comment]
Conversion and revenue increases amid terrible profit numbers:
https://www.just-style.com/news/drastic-change-required-at-debenhams-amid-fy-profit-warning_id132522.aspx

**Comment by tylersticka** [comment]
Closing this as there is a Debenhams submission with more details that was published 2+ years after this issue was created. Guessing this just slipped through the cracks.
