### ISSUE TITLE
Tinder

### ISSUE THREAD

**Issue by grigs** [cloudfour/pwastats#131]
### Summary

Tinder's PWA cut load times from 11.91s to 4.69s.

### Source

https://youtu.be/_srJ7eHS3IM?t=30m55s

### Tags

- Tag 1
- Tag 2

_List all that apply from the [tags directory](../_tags/)._

**Comment by derekshirk** [comment]
@grigs Additional Info on Tinder PWA. 

https://medium.com/@addyosmani/a-tinder-progressive-web-app-performance-case-study-78919d98ece0
