### ISSUE TITLE
Submission: New Story about Pinterest

### ISSUE THREAD

**Issue by tkadlec** [cloudfour/pwastats#133]
### Summary

Pinterest rebuilt their mobile site as a PWA and core engagements increase by 60%. They also saw a 44% increase in user-generated ad revenue and time spent on the site has increased by 40%.

### Source

https://medium.com/dev-channel/a-pinterest-progressive-web-app-performance-case-study-3bd6ed2e6154

### Tags

- Conversions
- Engagement
- App Shell
- Service Worker
- Offline
- Social

**Comment by tkadlec** [comment]
Whoops! Duplicates (but in my defense, adds onto) #125

**Comment by grigs** [comment]
Thanks @tkadlec!
