### ISSUE TITLE
Windows Phone 

### ISSUE THREAD

**Issue by mdrapps** [cloudfour/pwastats#139]
> **Note:** This template is for new case study content submissions only. 
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

e.g. _XYZ Company saw a 20% decrease in its landing page bounce rate after introducing service worker caching._

### Source

e.g. http://example.com/2017/article

### Tags

- Tag 1
- Tag 2

_List all that apply from the [tags directory](../_tags/)._

**Comment by tylersticka** [comment]
@mdrapps Please provide more information, including "Summary," "Source" and "Tags," as per the issue outline. Refer to [the live site](https://www.pwastats.com/) for examples. Thank you!

**Comment by tylersticka** [comment]
Closing this, as there's not enough detail for a story or a site issue. Please feel free to create a new issue with more information.
