### ISSUE TITLE
koolsol game offline

### ISSUE THREAD

**Issue by hugues-koolsol** [cloudfour/pwastats#143]
20% of the games won on koolsol are won offline, and not only in countries with reduced bandwidth but also in countries where players may have sometimes irregular connections (metro, train ...)

https://www.koolsol.com/

#game
#serviceworker 
#offline
![ks_192](https://user-images.githubusercontent.com/26767344/37362313-257af8f2-26f5-11e8-8f1a-ec4dcdda355d.png)

**Comment by grigs** [comment]
Sorry for not responding sooner. This is really neat to see. There's not a lot of data about offline usage in general. Do you have an article about the usage that we could link to?

**Comment by grigs** [comment]
I'm trying to clear the issues queue so I'm going to close this for now. If you have a link, please add a comment and reopen it.
