### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by agnelvishal** [cloudfour/pwastats#150]
### Summary
[Trusting Trust](https://agnelvishal.github.io/TrustingTrust/), an interactive story, saw an 500% increase in time spent on pwa app.

### Source

https://medium.com/@agnelvishal/trusting-trust-an-interactive-story-8be5f3098124

### Tags

- game

**Comment by grigs** [comment]
Sorry I didn't get to this sooner. Long story. The link is no longer working. Do you have a new one?

**Comment by grigs** [comment]
I'm trying to clear the issues queue so I'm going to close this for now. If you have an updated link, please add a comment and reopen it.
