### ISSUE TITLE
Submission: Commonfloor Groups

### ISSUE THREAD

**Issue by awebdeveloper** [cloudfour/pwastats#151]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary
Commonfloor groups saw 2x increase in DAU by moving to an app shell approach.

### Source

 https://medium.com/awebdeveloper/pwa-is-future-of-mobile-how-to-tame-it-855dd42df0ec

### Tags

- social
- e-commerce
- app-shell
- perforamance 

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by awebdeveloper** [comment]
@grigs anything more needs to be done to get this merged/approved

**Comment by grigs** [comment]
Thanks for flagging this for me. I don't know how I missed it. I've got a to do item to do a bunch of updates to PWA Stats. I'll try to get to it this week.

**Comment by awebdeveloper** [comment]
hi @grigs  do u need any help with this
