### ISSUE TITLE
Lead: Starbucks

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/pwastats#152]
### Summary

Saw this tweet from Google I/O:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">The <a href="https://twitter.com/Starbucks?ref_src=twsrc%5Etfw">@Starbucks</a> PWA resulted in 2x daily active users. We&#39;re seeing users order via the desktop at nearly the same rate of mobile browsers. <a href="https://twitter.com/hashtag/io18?src=hash&amp;ref_src=twsrc%5Etfw">#io18</a> <a href="https://t.co/qczusLBElF">pic.twitter.com/qczusLBElF</a></p>&mdash; David Brunelle @ Google I/O (@davidbrunelle) <a href="https://twitter.com/davidbrunelle/status/993960071406080000?ref_src=twsrc%5Etfw">May 8, 2018</a></blockquote>

I'd love to know if there's a better source for the stat, but thought I'd make an issue tracking it because Starbucks would make a great addition.

### Source

https://twitter.com/davidbrunelle/status/993960071406080000

### Tags

¯\\\_(ツ)_/¯

**Comment by grigs** [comment]
Found the source presentation at https://youtu.be/QCoQs9NO9q0?t=1871
