### ISSUE TITLE
Switch to Eleventy

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/pwastats#159]
In the discussion of #148, there's been some talk of further entrenching this project's build process in Node-land to better align with our pattern library.

I know we originally chose Jekyll because of its straightforwardness compared to the Node solutions at the time. Now, though, our pal Zach Leatherman made [eleventy](https://github.com/11ty/eleventy/) ~and there's an official [Vue-based static-site generator with built-in PWA support](https://vuepress.vuejs.org/).~

If we think at some point we might be drastically revising this project's build process _anyway_, it might make sense to consider a platform change.

Just food for thought! 🍔 

### Update

We've now used Eleventy half a dozen times and like it a lot. Zach works for Netlify now, so it's clearly the right choice given the build stack for this project. Let's do that!

---

@cloudfour/dev @cloudfour/pwastats

**Comment by calebeby** [comment]
Yeah, there are a lot to choose from, a good resource to look at is https://www.staticgen.com/

**Comment by calebeby** [comment]
I think I'm going to start with moving just the css part to node, and then we can decide whether or not we want to move the template part too

**Comment by tylersticka** [comment]
We should _definitely_ move to Eleventy. [It isn't hard to switch](https://24ways.org/2018/turn-jekyll-up-to-eleventy/), and it [keeps getting better](https://www.11ty.dev/docs/versions/).

**Comment by emersonthis** [comment]
I just pushed a work-in-progress branch: https://github.com/cloudfour/pwastats/tree/eleventy
The conversion is mostly complete, but the `/tags/*` pages aren't working yet but I ran out of time before having to put this down. 

Note to future self: here's a theoretically helpful link: https://www.11ty.dev/docs/quicktips/tag-pages/  ...but it's not currently working.
