### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by codecode31415** [cloudfour/pwastats#164]
Analytical tools for AliExpress buyers and sellers - alipic.net
Top features:
1. Product sales estimator by categories - Most selling products at AliExpress by categories (http://alipic.net/?param=prod-sold)
2. Top companies - Top sellers on AliExpress (http://alipic.net/?param=top-company)
3. Top items by countries - Top selling on AliExpress by counries (http://alipic.net/?param=top-country)
4. Top woman lingerie photos from feedback - Woman dress - users feedback (http://alipic.net/?param=woman-cat)

**Comment by tylersticka** [comment]
We only accept submissions that involve a PWA (alipic.net does not have a manifest file so it does not qualify), and only when there is data to show (not simply a feature list).
