### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by JoelEllis** [cloudfour/pwastats#165]
### Summary

_DerpMarine created a PWA as a game. the pwa takes less than 60ms to load for repeated visits and half a second for first loads on mobile devices. the application works online and offline, as a brilliant game to pass the time._

### Source

![image](https://user-images.githubusercontent.com/28905212/45264745-244d9580-b439-11e8-97c8-ad8a04a0046e.png)
https://offline-dino-game.firebaseapp.com/

### Tags

- Performance
- Speed
- Offline

**Comment by grigs** [comment]
Sounds like this was a new app. Typically, we feature apps that show the improvements from implementing a PWA. That's harder to do with a new app.

We also need an article to link to.

**Comment by JoelEllis** [comment]
Well sheesh this was a long time ago. Sorry this can't be useful to you, as there is no article or previous, non PWA, version.

**Comment by grigs** [comment]
Thanks @JoelEllis. Like I said, I'm sorry for the massive delay. The last year and a half or so has been consumed by family health issues. :(

**Comment by JoelEllis** [comment]
Oh, I'm sorry about that. The delay is fine, this isn't your job!
