### ISSUE TITLE
Submission: Condense.Press

### ISSUE THREAD

**Issue by agnelvishal** [cloudfour/pwastats#180]
### Summary

e.g. [Condense.press](https://www.condense.press/) bought page load time down by 50% and engagements rose by 10% by using service worker cache.
### Source

https://medium.com/@agnelvishal/i-believe-there-is-a-better-way-to-pick-what-to-read-5d57ab80972a

### Tags

- News
- Media

**Comment by grigs** [comment]
I'm sorry I didn't get to this earlier. The medium link is no longer working. Has it been published elsewhere?

**Comment by grigs** [comment]
After I posted the previous comment, I realized that I need to clear the issues queue so it is easier to see what is actionable. I'm going to close this issue for now, but if you have an updated link, please add a comment and reopen it.
