### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by eludi** [cloudfour/pwastats#181]
### Summary

elowo is a new hackable Portable Web App (PWA) that enables you to easily create web apps yourself, even on mobile devices!

![elowo logo](https://elowo.eludi.net/icon152.png)

### Source

https://elowo.eludi.net/doc.html

### Tags

- News
- Service Worker

**Comment by tylersticka** [comment]
@eludi Thank you for your submission.

PWA Stats is meant to showcase statistics related to the performance of Progressive Web Apps. You can [browse the other features](https://www.pwastats.com/) to see examples, noting that they all feature some sort of quantifiable measure of success. For example, one post is "The Best Western River North Hotel sees *300%* increase in revenue with new Progressive Web App." They also require a source that contains that same information.

Do you have a statistic and supporting article or resource that would meet these requirements?

**Comment by eludi** [comment]
@tylersticka thank you for these clarifications!

The mentioned PWA is rather new, so we do not have any statistically grounded success story yet. As soon as we have respective material, we will open a more appropriate story proposal.

**Comment by tylersticka** [comment]
@eludi Sounds great, we look forward to it! 🙂
