### ISSUE TITLE
Submission: Building ViecDuLich PWA Success

### ISSUE THREAD

**Issue by vankhuong** [cloudfour/pwastats#183]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

**ViecDuLich** has been oriented to use PWAs technical from the first version, the application is too fast and light on both mobile and desktop, the homepage completely loads in **0.5** seconds and passed Lighthouse with **100%** performance.

### Source

e.g. https://medium.com/@khuongngo/building-viecdulich-com-pwa-success-712680d1968d

### Tags

- Performance
- Service Worker
- News
- Offline
- Home Screen

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by grigs** [comment]
Congratulations! We'd love to include ViecDuLich in PWA Stats. What we're looking for is statistics on how the PWA performed. For example, the amount of speed improvement, conversions increases, etc.

Do you have any data like that?
