### ISSUE TITLE
Submission: New Story (Technodom.kz)

### ISSUE THREAD

**Issue by aleksandrsho** [cloudfour/pwastats#184]
### Summary

With 34 stores, 60,000 products in each, and 15,000 product attributes, Technodom.kz has become the biggest Magento PWA in the world!

### Source

e.g. https://medium.com/progressivewebapps/scandiweb-launched-the-biggest-pwa-store-on-magento-b348067e291b

### Tags

-E-commerce
-Home Screen
-Offline
-Service Worker

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by grigs** [comment]
Congratulations. When you have some data about how the PWA is performing, please let us know. We only link to articles that share statistics about how a PWA is doing.
