### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by adarshmadrecha** [cloudfour/pwastats#185]
### Summary
Jamku, an compliance management software saw a 200% increase in user engagement after launching PWA on desktop and Mobile.

### Source
https://madrecha.com/jamku

### Tags
- offline
- performance
- b2b

**Comment by tylersticka** [comment]
Thank you, @adarshmadrecha.

I can't find that statistic cited at the URL you provided. Is there a specific article, blog post, tweet, presentation or other resource we could link to where the 200% increase is mentioned specifically?

**Comment by adarshmadrecha** [comment]
I misinterpritted the field. Will share the statstics page in sometime.

**Comment by grigs** [comment]
I'm attempting to clear the issues queue so it is easier to see what is actionable. I'm going to close this issue for now, but if you have a link to share, please add a comment and reopen it.
