### ISSUE TITLE
Submission: PROGRESSIVE WEB APPS: EVERYTHING YOU NEED TO KNOW

### ISSUE THREAD

**Issue by garrysmith010** [cloudfour/pwastats#187]
Are you curious to know about PWA and how they can be useful for your business? PWA or Progressive Web Apps is a great technology that is revolutionizing the mobile app industry. In our blog, you will get complete information [about progressive web apps](https://www.csschopper.com/blog/progressive-web-apps-everything-you-need-to-know/). You can know what a PWA is, what features they provide to users, what components they are built from, technologies that are utilized for developing PWAs and much other useful information. Go through the blog to get a deep insight into PWA. If you want to know more, you can click here to know.

**Comment by tylersticka** [comment]
We do not accept submissions that are wholly promotional in content.

If one of your customers eventually shares data or statistics related to a specific progressive web app we haven't yet documented, that would make a great submission. Thanks!
