### ISSUE TITLE
Broken Footer Image

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/pwastats#188]
In the footer we're hotlinking an image from cloudfour.com, but it appears that image is now hosted on a CDN instead of directly on the Cloud Four domain. This leads to a broken image, which shows alt text instead of a graphic (Portland, Oregon Landscape):

<img width="1440" alt="Screen Shot 2020-01-28 at 10 25 16 AM" src="https://user-images.githubusercontent.com/5798536/73251173-b8e49f00-41b8-11ea-8977-11c61d3ad7a6.png">

---

I was going to copy that image over to this repo, but wasn't sure where it belonged given the project structure. It seems like the `images` directory is primarily used to store PWA icons. Is there a better place to put it? Should we use inline SVGs instead? Base 64 Data URIs?

@tylersticka if you could provide some guidance when you have some time I'd be happy to put up a PR fixing this. Thanks!

**Comment by tylersticka** [comment]
@Paul-Hebert I don't have a particular opinion on where/how this should be stored!

**Comment by derekshirk** [comment]
Good catch @Paul-Hebert.

**Comment by Paul-Hebert** [comment]
Sounds good, thanks!
