### ISSUE TITLE
Submission: New Story (asphaltgold)

### ISSUE THREAD

**Issue by bjoern-flagbit** [cloudfour/pwastats#193]
### Summary

The complete e-commerce platform was replaced in November 2019 by a PWA solution based on angular. asphaltgold GmbH & Co. KG saw a reduction for the bounce rate by 57% compared january 2020 with previous year. Pageviews increased by 128% over the same period. This also resulted in a significant increase in sales.

### Source

https://www.asphaltgold.com/

### Tags

- e-commerce
- payment
- service-worker

**Comment by tylersticka** [comment]
Thank you for your submission, @bjoern-flagbit.

I don't see these numbers verified at the source URL you provided (https://www.asphaltgold.com/). Is there a blog post, tweet, presentation, etc. where those numbers have been shared?

**Comment by bjoern-flagbit** [comment]
Not yet. Need to talk with the customer first. Will provide the link after that.

**Comment by grigs** [comment]
I hope the data is published and we can link to it. In the meantime, I'm closing the issue to clean our queue.
