### ISSUE TITLE
Submission: Rooted Objects

### ISSUE THREAD

**Issue by piyushlathiya** [cloudfour/pwastats#197]
### Summary

Fashion Brand **Rooted Objects** saw **162%** higher conversation rate by moving to Progressive Web Apps. The page load time was decreased by **25%** while the average redirection time was decreased by **80%**. ![RootedObjects](https://user-images.githubusercontent.com/1814821/79344654-bb4fcd00-7f4d-11ea-8c32-8b7ca3e26708.png)

### Source

https://aureatelabs.com/case-studies/rooted-objects-magento-2-pwa/

### Tags

- Conversions
- E-Commerce
- Performance
- Revenue

**Comment by grigs** [comment]
This is stellar. Thank you for submitting it.
