### ISSUE TITLE
Submission: Kubota story

### ISSUE THREAD

**Issue by cnviradiya** [cloudfour/pwastats#200]
### Summary
Fashion brand launching PWA in mobile-first store
Kubota is an iconic Polish fashion brand that tuned towards modern eCommerce trends, mobile-first and PWA included, to rollout the famous shoe brand back on the market with over 1000 orders in the first month.

### Source
https://www.vuestorefront.io/kubota-case-study/
https://divante.com/blog/kubotas-case-study-of-launching-pwa-in-mobile-first-store/

### Tags

- Offline
- Conversions
- Performance
- Service-worker
- Instant-checkout
- Vue-storefront

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by emersonthis** [comment]
@cnviradiya Thanks for submitting this. Do you happen to know the site these case studies are describing? I am having a surprisingly hard time finding it.

**Comment by emersonthis** [comment]
@cnviradiya Nevermind. It looks like we found it: https://www.kubotastore.pl/
