### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by mattruddy** [cloudfour/pwastats#202]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

There is now a well maintained PWA Store to discover Progressive Web Apps. The PWA Store has around 150 PWAs uploaded with over 50k installs.

### Source

https://progressiveapp.store/pwas

### Tags

- news
- media

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by tylersticka** [comment]
Thank you for your submission.

A few questions:

1. How are you tracking installs?
1. I do not see the stats you shared at the URL provided. Do you have an article, blog post, tweet, etc.?

**Comment by mattruddy** [comment]
1) Every-time a user clicks the "Free" button, we could that as an install for the PWA.

2) PWA Store was on the front the front page of HackerNews 

https://news.ycombinator.com/item?id=22963822

also in the hacker newsletter

https://www.abovo.co/kale@hackernewsletter.com/69984

**Comment by tylersticka** [comment]
It looks like a cool resource!

The links you've submitted don't satisfy the requirements for inclusion on this site, but feel free to submit again in the future if you ever share an article that includes more usage details.

**Comment by mattruddy** [comment]
what types of articles meet that criteria

**Comment by tylersticka** [comment]
I recommend clicking through [our recent entries](https://www.pwastats.com/) for examples. None of the links are to the PWAs themselves, but to stories, presentations or prominent contributor comments that support the data _about_ the PWA in question.
