### ISSUE TITLE
[Eleventy] Contribute a Story button not working properly

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/pwastats#213]
Clicking on the Contribute a Story button on the preview site takes you to an (adorable, yet unexpected) error page:
![404](https://user-images.githubusercontent.com/66242/86949649-d290f780-c103-11ea-9bea-e5c308af0378.gif)

**Comment by megnotarte** [comment]
Same behavior occurs when the user clicks the Create an Issue button the error screen.

**Comment by emersonthis** [comment]
Fixed
