### ISSUE TITLE
Is the Twitter IFTTT integration working?

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/pwastats#220]
The 11ty rebuild (#206) was merged about a week ago. We just published our first stat (since that refactor) today (#200). After ~30min the new tweet had not appeared in the feed yet, so I got antsy and started investigating. 

I didn't see any activity in the IFTTT logs (but did see some mysterious errors from a week or two ago). I eventually clicked a button to "check" the connection/feed and the tweet immediately appeared. This _probably_ means I just didn't wait long enough. There's some anecdotal evidence that IFTTT is running more slowly these days. But I'm documenting this in case this turns out to be a problem. 

Full conversation on this Slack thread
https://cloudfour.slack.com/archives/C4MH72HQF/p1595443863004800

- [x] Post another stat
- [x] Wait patiently for the tweet to show up
- [x] If it eventually does, close this issue
- [x] If there's no action within a day or so, start troubleshooting...

**Comment by tylersticka** [comment]
Closing this issue as the IFTTT integration now requires a "pro" account, presumably due to Twitter's new payment structure for API access. So the integration is not working, but that's for a known reason.
