### ISSUE TITLE
Burcher of Blue

### ISSUE THREAD

**Issue by KGR-1** [cloudfour/pwastats#223]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

Butcher of Blue implemented the PWA, and soon after, the number of its mobile users grew by **154%** and conversion rate - by **169%**.

### Source

https://www.vuestorefront.io/case-studies/butcher-of-blue

### Tags

- #Conversion
- #E-commerce
- #Fashion

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by grigs** [comment]
FYI, your manifest file contains a reference to a file that doesn't exist:
```
    {
      "src": "/assets/android-icon-192x192.png",
      "type": "image/png",
      "sizes": "512x512"
    }
```

You'll see the error in the Application tab in Chrome:
<img width="557" alt="Screen Shot 2020-10-12 at 4 03 39 PM" src="https://user-images.githubusercontent.com/804237/95797508-917d2600-0ca4-11eb-849f-4ad46030d767.png">
