### ISSUE TITLE
Submission: Gamesonline.co.id

### ISSUE THREAD

**Issue by siblibusro87** [cloudfour/pwastats#232]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

PWA help better performance on gamesonline.co.id it redue load time to become faster and make the portal free games online on indonesian comunity
### Source

https://gamesonline.co.id/

### Tags

- Games 
- Online
- Free

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by grigs** [comment]
Thanks @siblibusro87. Are there any stats for the improvement that are published somewhere?

**Comment by tylersticka** [comment]
Closing this since we haven't heard back with any specific statistics. Please feel free to re-open if/when you've publish specific details.
