### ISSUE TITLE
Submission: RSSAnt - RSS Reader

### ISSUE THREAD

**Issue by guyskk** [cloudfour/pwastats#238]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

PWA make the RSS reader website installable, the experience is more smooth after add to home screen, and saves the effort to develop App. To maximize the compatibility, the website support enable/disable PWA manually.

### Source

URL: https://rss.anyant.com/?pwa=1
GitHub: https://github.com/anyant/rssant

### Tags

- App Shell
- Home Screen
- Open Source
- RSS Reader

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by tylersticka** [comment]
@guyskk Looks like a cool project!

Unfortunately we can't accept submissions that don't include statistics. If you [browse our other entries](https://www.pwastats.com/), you'll notice that they don't link to the apps themselves, but to articles, tweets, etc. that detail specific stats related to adopting PWA technologies.

There are several other projects that exist as directories of PWAs, including [findPWA](https://findpwa.com/), [PWA.ninja Directory](https://pwa.ninja/directory) and [Appscope](https://appsco.pe/).

Feel free to submit again if you eventually write an article or provide specific stats in a shareable format! Have a great day!

**Comment by guyskk** [comment]
Got it, thank you!
