### ISSUE TITLE
KKTC-Deprem

### ISSUE THREAD

**Issue by myozden** [cloudfour/pwastats#259]
KTTC-Deprem sitesi Türkiye ve Kıbrıs bölgesinde olan deprem bilgilerini paylaşmak ve olası depremlerden önce ve anında gereken bilgileri paylaşma amacıyla hazırlanmış bir sitedir. 

---

### Summary
KTTC-Deprem ilk elden deprem bilgisi.

### Source

https://kktcdeprem.net

**Comment by tylersticka** [comment]
Thank you for your submission, @myozden.

Unfortunately we are only accepting submissions that include statistics related to site performance with URL representing the source of those statistics.

Please feel free to resubmit when/if there is a published article/talk/etc. with statistics related to the project’s performance as a PWA.
