### ISSUE TITLE
Submission: New Story

### ISSUE THREAD

**Issue by rachaelfrontcommerce** [cloudfour/pwastats#261]
### Summary

_Kaporal leans on Front-Commerce to improve online engagement. A 60% drop in bounce rate on all devices, linked to the positive impact on the site’s display performance and speed. Increase in overall conversion rate: +15% on desktop and +8% on mobile. Increase in site engagement with a positive increase in the number of page views (especially the product catalog): +40% and in the useful time spent on the site +8% _

### Source

https://www.front-commerce.com/improve-online-engagement-kaporal-case-study/

### Tags

- Performance
- Fashion
- E-commerce
- Conversions

**Comment by tylersticka** [comment]
@rachaelfrontcommerce Thank you for your submission.

The case study mentions "the PWA standard" but does not highlight any specific features. Can you provide more context?

Also, the text of this submission highlights Front-Commerce but not any PWA technology. To keep this a useful resource, we need the connection between PWA features and the resulting statistics to be clear without the reader having to draw the connections themselves. That means the examples need to sing the praises of PWA features over a particular agency or execution (though obviously that info can be part of the linked case study).

**Comment by rachaelfrontcommerce** [comment]
Hi Tyler,
I've updated the case study with the following info. Let me know if anything else needs adding

- A 60% drop in the bounce rate on all devices, linked to the positive impact on the site's display performance and speed: faster page loading.
- Increase in overall conversion rate: +15% on desktop and +8% on mobile du to a smoother user experience and responsive UX.
- Increase in site engagement with a positive increase in the number of page views (especially the product catalog): +40% and in the useful time spent on the site +8%, due to fluid navigation, ultra-fast page loading
