### ISSUE TITLE
"PWA Stats" heading :focus should be less subtle

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#43]
When tabbing through the links on the page, the `:focus` state of the "PWA Stats" heading seems a bit too subtle. 

![screen shot 2017-04-05 at 10 08 07 am](https://cloud.githubusercontent.com/assets/459757/24717727/502da862-19e8-11e7-84d6-3ab02a7e7fad.png)

**Comment by tylersticka** [comment]
It actually needs an `id` and an `aria-describedby` attribute. See: https://css-tricks.com/accessible-svgs/#article-header-id-6

**Comment by gerardo-rodriguez** [comment]
@tylersticka Was your suggestion for this issue or #44?

**Comment by tylersticka** [comment]
🤦‍♂️
