### ISSUE TITLE
Change company image alt attribute?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#49]
In [this PR](https://github.com/cloudfour/pwastats/pull/45/files#diff-99b8a848eee0e97d8fbb714cd0760a47R4), I dropped in the company name into the company image `alt` attribute. When using voiceover, though, this gets read as well as the summary. In some cases, it sounds odd to hear the company name used twice, back-to-back. For example, the PureFormulas card will read:
> PureFormulas PureFormulas’ PWA saw 23% higher revenue than the m.dot website it replaced.

Should the [`alt` attribute](https://github.com/cloudfour/pwastats/blob/master/_includes/resource-item.html#L4) be modified to something else?

**Comment by gerardo-rodriguez** [comment]
Was reading through this: http://webaim.org/techniques/alttext/

> If the content that the image conveys is presented within text in the surrounding context of the image, then an empty alt attribute may suffice.

**Comment by tylersticka** [comment]
Yeah, the `alt` attributes should definitely be empty.
