### ISSUE TITLE
Issue template should include all tags

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#55]
## Summary

Our [Issue Template](https://github.com/cloudfour/pwastats/blob/master/.github/ISSUE_TEMPLATE.md) tags list is outdated. We've added some new tags in #47 and #54 that need to be included as options in the Issue Template.

**Comment by tylersticka** [comment]
Would it be more sustainable to link to the tags directory or something?

**Comment by gerardo-rodriguez** [comment]
> Would it be more sustainable to link to the tags directory or something?

I like your thinking here. Yeah, seems like linking to the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags) might make the most sense? ¯\\\_(ツ)_/¯

**Comment by erikjung** [comment]
I acknowledge and approve of this idea.
