### ISSUE TITLE
Submit to pwa.rocks

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#68]
https://github.com/pwarocks/pwa.rocks

**Comment by grigs** [comment]
@gerardo-rodriguez are you doing this?

**Comment by gerardo-rodriguez** [comment]
@grigs Nope, this issue is unassigned at the moment, but I can assign it to myself and take care of it if you'd like me to. 😉

**Comment by gerardo-rodriguez** [comment]
Submission made: https://github.com/pwarocks/pwa.rocks/pull/218
