### ISSUE TITLE
SW not handling our image assets?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#71]
It appears the [asset route](https://github.com/cloudfour/pwastats/blob/master/sw.js#L28-L31) in our `sw.js` file is only concerned for our CSS & JS files. Should the image assets also be accounted for?

**Comment by grigs** [comment]
Further, CSS is not getting cached. The following is the network timeline with the offline button checked:
<img width="832" alt="screen shot 2017-04-07 at 11 32 26 am" src="https://cloud.githubusercontent.com/assets/804237/24814307/fd704752-1b85-11e7-9d2f-71ee78355909.png">

**Comment by erikjung** [comment]
@grigs Those red line items are expected...the requests are 404ing _before_ falling back to the cache. If you look in the cache storage, you should see `toolkit.css` listed. Also, the page would appear to have no styles otherwise.
