### ISSUE TITLE
Update to license

### ISSUE THREAD

**Issue by grigs** [cloudfour/pwastats#80]
Because we stole the footer from Cloud Four's site, the license lists it as being copyrighted. I'd like to update that in a way that makes it clear that the content and code are all open source. But I'd also like to make it clear that our logo and the portions of the design that are uniquely Cloud Four are still something we retain rights to.

I was thinking about saying something like:

Content and code licensed under a [Creative Commons](https://creativecommons.org/licenses/by/4.0/).  Logos and design © 2007 - 2017 Cloud Four, Inc.

Does that make sound good? If so, can someone add it?

**Comment by grigs** [comment]
Or should it be MIT license because it is talking about code as well? The content seems like a natural fit for Creative Commons. The code for MIT license. But having three licenses for a simple site seems silly.

**Comment by erikjung** [comment]
> Or should it be MIT license because it is talking about code as well? 

Unsure how this applies...there won't actually be any code _content_ on the site, right?

**Comment by tylersticka** [comment]
I can't find a lot of examples of sites advertising the code or content license, most seem to leave that to the GitHub repo.

I _do_ think it might be worth softening the byline and linking to the license in the repo (which doesn't appear to be any more or less permissive than Creative Commons):

<img width="771" alt="screen shot 2017-04-11 at 11 21 48 am" src="https://cloud.githubusercontent.com/assets/69633/24924295/27ac4c84-1ea9-11e7-8d5f-7167b7df5bff.png">

That would seem to be going above and beyond what WPO Stats and Website Style Guide Reference do.

(Having a © symbol doesn't provide us any additional copyright protection, it's mostly an aesthetic/legitimacy thing on our main site.)

**Comment by grigs** [comment]
This is ok for now.
