### ISSUE TITLE
Should posts have an author?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#83]
See:
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.pwastats.com%2Ffeed.xml
- https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.pwastats.com%2Ffeed.xml

> line 2, column 116: name should not be blank (10 occurrences) 

See [`jekyll-feed` docs](https://github.com/jekyll/jekyll-feed#usage) for info on setting `author` value.

**Comment by tylersticka** [comment]
@gerardo-rodriguez Can we add a default "Cloud Four" or "PWA Community" value?

**Comment by gerardo-rodriguez** [comment]
> Can we add a default "Cloud Four" or "PWA Community" value?

@tylersticka I like the "PWA Community" idea, I'll look into it.
