### ISSUE TITLE
Feed images are not coming through

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#86]
See: http://carp.docs.geckotribe.com/feed-test.php?feed=https%3A%2F%2Fwww.pwastats.com%2Ffeed.xml

**Comment by gerardo-rodriguez** [comment]
Notice the path: `https://www.pwastats.com/twitter-lite.png`

It should be: `https://www.pwastats.com/images/twitter-lite.png`

**Comment by tylersticka** [comment]
I didn't even think the image would show up in the feed... 😮

Umm... I guess we could update the `resource-item` template and update the posts with full paths?

**Comment by erikjung** [comment]
I assume the issue is that our post front matter has no paths for the images.

**Comment by gerardo-rodriguez** [comment]
> Umm... I guess we could update the resource-item template and update the posts with full paths?

@tylersticka Yep, trying that right now. Updating posts to `/images/twitter-light.png`
